#!/usr/bin/python
# -*- coding: UTF-8 -*-

import sqlite3
import requests
import hmac
import hashlib
import time
from datetime import datetime
import MySQLdb
import sys

coins=["doge", "met", "plc", "jbc", "skt", "tfc", "mtc", "ifc", "dnc", "xrp", "max", "bts", "rss", "etc"]
sigure_keywords = ["1", "10000", "buy", "141377098123", "3aky3-9qyjt-t7n5k-aggtu-d78rq-fatag-fcs1a"]
secret="@m3,.-/O3DZ-OYj7K-7BZrg-EZFm4-$VxYX-VN~Xy"
payload = {"amount":1, "price":"10000", "type":"buy", "nonce":"141377098123",
    "key":"3aky3-9qyjt-t7n5k-aggtu-d78rq-fatag-fcs1a",
	"signature": hmac.new(secret, msg="&".join(sigure_keywords), digestmod=hashlib.sha256).hexdigest(),
	"coin":""}


def add_mysql(name, ticker):
	try:
		db = MySQLdb.connect("localhost", "root", "123456", "coins")
		sql = 'INSERT INTO coins(NAME, PRICE, AMOUNT, TIME) VALUES("%s", "%s", "%s", "%s")' % (name, ticker[u"sell"], ticker["volume"], datetime.now())
		cursor = db.cursor()
		cursor.execute(sql)
		db.commit()
		db.close()
	except:
		print "add recorder error"

def get_data():
	while True:
		for coin in coins:
			try:
				payload["coin"] = coin
				ticker = requests.get("https://www.jubi.com/api/v1/ticker", params=payload, timeout=3).json()
			except:
				print "get %s ticker error" % (coin)
				continue
			add_mysql(coin, ticker)
		time.sleep(1)

def move_data():
	conn = sqlite3.connect('coins.db')
	db = MySQLdb.connect("localhost", "root", "123456", "coins")
	mysql = db.cursor()

	cursor = conn.execute("select * from coins")
	for row in cursor:
		sql = sql = 'INSERT INTO coins(NAME, PRICE, AMOUNT, TIME) VALUES("%s", "%s", "%s", "%s")' % (row[1], row[2], "0", row[3])
		mysql.execute(sql)
		db.commit()

	conn.close()
	db.close()

if __name__ == '__main__':
	if sys.argv[1] == "collect":
		get_data()
	elif sys.argv[1] == "mysql":
		move_data()
	else:
		pass
